### ISSUE TITLE
Feature Request: Export and import triggers using a plain text file (JSON/XML) for manual editing

### ISSUE THREAD

**Issue by ElGoncen** [KSneijders/AoE2ScenarioParser#17]
I do not know if that function exists but if it would not be useful to put the possibility of exporting to a plain text file (for example an XML) that contains the triggers of a scan so that one can edit it manually and then import it to another scenario or modify until correcting an existing one. This would serve to have trigger templates to be able to alter it to our needs. Not only change what conditions go to each player but edit more for example types of armor, quantity of it, names of civilizations etc. Even to share trigger tables. Something similar to what could be done with the AOKTS
What do you think?

**Comment by KSneijders** [comment]
Hey, thanks for the feature request 🙂
It does sound like a useful feature, especially for people who have few to no experience in programming.
I'd have to think about how it'd work exactly but I do like the sound of it.
Just to be sure, AOKTS doesn't have a way to import those triggers back into a scenario, right? 
I know about the export feature. 
I'll look into it but can't promise anything right now. I'll send an update here if I have one 🙂

**Comment by ElGoncen** [comment]
Hello.
The AOKTS has no way of importing or exporting triggers, what I meant is that the AOKTS has the option to see the triggers in plain text and from there one can copy them to a text editor, manipulate it and save it to later copy them back to the editor. of the AOKTS in that or another scenario.

https://i.imgur.com/F3ma7tf.png

Thank you for taking the proposal seriously, I am very glad that you liked the idea. If in future versions one can export the triggers to an XML or a JSON to modify or save them and also import them to the designers, it would save us a lot of time. Even so, with those options it has, it is quite useful at the moment.

Greetings

**Comment by KSneijders** [comment]
@ElGoncen Hey, it's been a loooonng time since I've looked at this, sorry for the lack of communication.

Whilst I think this *might* be useful to some people. 
I'd like to focus more on getting people to use the actual library to solve their problems.

Whilst it'd work with plain text files, it'd be very clunky as missing just a single token, or certain keys in a construct would cause it to fail. 
I can see how this could be useful for making small changes to a scenario but at that point the editor itself might be of more use.
