### ISSUE TITLE
Does get_trigger() not accept trigger_index or display_index as parms any more?

### ISSUE THREAD

**Issue by newtonerdai** [KSneijders/AoE2ScenarioParser#6]
My Python version: 3.8.2
My AoE2ScenarioParser version: 0.0.9

When I am testing the example for `get_trigger()` in [TRIGGERS.md - Editing triggers, conditions or effects](https://github.com/KSneijders/AoE2ScenarioParser/blob/master/cheatsheets/TRIGGERS.md#editing-triggers-conditions-or-effects):
```python
trigger = trigger_manager.get_trigger(trigger_index=0)
trigger = trigger_manager.get_trigger(display_index=0)
```
then Errors raised:
```
TypeError: get_trigger() got an unexpected keyword argument 'trigger_index'
TypeError: get_trigger() got an unexpected keyword argument 'display_index'
```
Here is the source code of `get_trigger()`:
https://github.com/KSneijders/AoE2ScenarioParser/blob/b6025a39ba160415de8481ed36fbc894fff9aff6/AoE2ScenarioParser/objects/triggers_obj.py#L380

Seemingly the function has changed after TRIGGERS.md submitted.

**Comment by KSneijders** [comment]
Hey, sorry for the confusion. Since verion 0.0.8 (released this week) the way to select triggers changed. The reason for this was the cluttering of parameters in all functions (`trigger_index`, `display_index `and `trigger`). Instead it has changed to an object (`TriggerSelect`). 

You can now use it like so: `TriggerSelect(trigger_index=0)` or for short: `TS.index(0)`. 

Hope it works this way and thanks for creating an issue about it!

**Comment by newtonerdai** [comment]
Ah, so that's it. TriggerSelect works well!
Well, it is time to update TRIGGERS.md~
Thanks.

**Comment by KSneijders** [comment]
Yeah it was brought to my attention a little earlier today that I didn't update those. Sorry for that 🤦‍♂️ 
I'm in the process of moving the docs to: https://aoe2scenarioparser.readthedocs.io/en/master/ and I updated those. Will update the cheatsheets later today!

**Comment by KSneijders** [comment]
I've updated the cheatsheet accordingly, let me know if you find any more outdated docs! 👍
